name: Lint Code Base

on: push

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    env:
      PYTHON: '3.8.8'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        DEFAULT_BRNACH: master
        GITGUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_FLAKE8: true
    